name: telsis-translator-flutter
version: 0.1.2
summary: Telsis language translator
description: App that translates to and from the Telsis language

confinement: strict
base: core18
grade: stable
   
apps:
  telsis-translator-flutter:
    command: telsis_translator_flutter
    extensions: [flutter-master] # Where "master" defines which Flutter channel to use for the build
    plugs:
    - network
parts:
  telsis-translator-flutter:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
