name: telsis-translator-flutter
version: 0.2.0
summary: Telsis language translator
description: App that translates to and from the Telsis language used in the Violet Evergarden series

confinement: strict
base: core18
grade: stable
   
#slots:
#  dbus-telsis-translator-flutter:
#    interface: dbus
#    bus: session
#    name: com.maplerain.telsis_translator_flutter

apps:
  telsis-translator-flutter:
    command: telsis_translator_flutter
    extensions: [flutter-stable] # Where "master" defines which Flutter channel to use for the build
    plugs:
    - network
parts:
  telsis-translator-flutter:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
    override-pull: |
      set -eux
      rm -rf $SNAPCRAFT_PROJECT_DIR/build
      snapcraftctl pull
